# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import tree.dbarray


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', tree.dbarray.IntegerArrayField(blank=True, editable=False)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
