# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
    ]
